project_id = "lwadfvkaywbdebvwdfgb"

[functions]
  [functions.admin-delete-user]
    verify_jwt = false
  [functions.admin-invite-user]
    verify_jwt = false
  [functions.admin-reset-password]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.evaluate-answer]
    verify_jwt = false
  [functions.generate-barema]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.transcribe-answer]
    verify_jwt = false
  [functions.create-turma-checkout]
    verify_jwt = false
  [functions.stripe-turma-webhook]
    verify_jwt = false
  [functions.hotmart-webhook]
    verify_jwt = false
