project_id = "lwadfvkaywbdebvwdfgb"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.generate-barema]
verify_jwt = false
